name: Feature Request
description: Suggest a new feature or enhancement for WirelessPen
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        
        Thank you for suggesting a new feature! Please provide details about what you'd like to see added to WirelessPen.
        
        **Before submitting:**
        - [ ] I have searched existing issues to avoid duplicates
        - [ ] I have read the [Technical Documentation](../../doc/technical.md)
        - [ ] This feature aligns with the project's ethical guidelines

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Attack Modes
        - User Interface
        - Hardware Support
        - Performance
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with research and planning
        - label: I can help with coding/implementation
        - label: I can help with testing
        - label: I can help with documentation
        - label: I would just like to suggest the idea

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas?
      placeholder: |
        - Dependencies required
        - Performance impact
        - Security considerations
        - Compatibility concerns

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...